feat: always use force flag or enrollment allowed setting
openedx/openedx-wordpress-ecommerce pull request #57
Opened 2023-10-26 01:25 UTC by julianramirez2

## Description

Now, in the 'Settings' tab of the plugin, you will find a field titled 'Advanced Settings' that allows you to configure whether the program should ALWAYS use 'force' or 'enrollment allowed' in all requests.

## Testing instructions

Pull the branch locally and run the 'composer install' command to install all plugin dependencies and test.

## Additional information

This is how the settings look now:

![image](https://github.com/openedx/openedx-wordpress-ecommerce/assets/52968528/3d93f807-d700-4856-bbea-5828912634e2)

## Checklist for Merge

- [X] Tested in a remote environment
- [ ] Updated documentation N/A
- [ ] Rebased master/main N/A
- [ ] Squashed commits N/A

2023-10-26 01:25 UTC, openedx-webhooks commented
Thanks for the pull request, @julianramirez2!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-10-27 21:33 UTC, MaferMazu requested changes
Thanks for this PR @julianramirez2.
I think we can improve this, because the feature is that you can set the force flag and the enrollment allowed as the default behavior for the automatic functions (fulfillment and refund), but with this we are setting it always.

Another problem I found with this implementation is that changes not are reflected in the request. For example, I select to use always the enrollment allowed and in my request when I buy the item, the plugin takes into account my advanced setting, but is not in the request:
![Screenshot from 2023-10-27 16-06-23](https://github.com/openedx/openedx-wordpress-ecommerce/assets/35668326/7ec90988-01a8-4fd8-ab44-c5705334df7a)
Screenshot of an enrollment request with enrollment allowed and I don't see the check marked.

The same happened if I create a new enrollment request manually. I can't have a custom behavior here. 
![Screenshot from 2023-10-27 16-11-17](https://github.com/openedx/openedx-wordpress-ecommerce/assets/35668326/44d15be6-00b3-4eac-9d80-1aeaaf6d78ac)
Screenshot of a manual request without force and enrollment allowed, and the plugin is using the advanced settings.

Note: another weird behavior I found about this is that the always only works at the first call (I think it is because we are not marking the checks in the request).
Let me explain: I create a enrollment request without the check marked in the request (but in the advance settings I have marked both); when I create the object they use the always, but if I select Save and update again is not taking into account the always settings.

![image](https://github.com/openedx/openedx-wordpress-ecommerce/assets/35668326/12e33db2-5b8b-4889-91ec-be428156d3db)
Screenshot of the same request with the same form and parameters, but different answers.

2023-11-01 23:59 UTC, MaferMazu commented
I will close this for now because it's not a priority, and we must implement it differently. Then, we can reopen or create another PR about this.

2023-11-01 23:59 UTC, closed without merging

2023-11-01 23:59 UTC, openedx-webhooks commented
@julianramirez2 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-wordpress-ecommerce&entry.867055334=https://github.com/openedx/openedx-wordpress-ecommerce/pull/57&entry.1484655318=https://github.com/julianramirez2&entry.752974735=2023-10-26+01:25&entry.1917517419=2023-11-01+23:59&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->

2023-11-01 23:59 UTC, openedx-webhooks commented
@julianramirez2 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-wordpress-ecommerce&entry.867055334=https://github.com/openedx/openedx-wordpress-ecommerce/pull/57&entry.1484655318=https://github.com/julianramirez2&entry.752974735=2023-10-26+01:25&entry.1917517419=2023-11-01+23:59&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->